name: Sync Winget Packages

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'winget/**'

jobs:
  sync-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run sync_packages.py
        run: |
          python3 winget/sync_packages.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/winget/*.json
          if ! git diff --cached --quiet; then
            git commit -m "chore: auto-sync winget package files"
            git push origin HEAD:${{ github.head_ref }}
          fi

      - name: Comment on PR with updated files
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          UPDATED_FILES=$(git diff --name-only HEAD^ HEAD | grep '^docs/winget/' || true)
          if [ -n "$UPDATED_FILES" ]; then
            MSG="The following files were updated by the sync workflow:\n\n\`\`\`\n$UPDATED_FILES\n\`\`\`"
            PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
            gh pr comment "$PR_NUMBER" --body "$MSG"
          fi
