name: Sync Winget Packages

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'winget/**'

jobs:
  sync-packages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run sync_packages.py
        working-directory: winget
        run: |
          python3 sync_packages.py

      - name: Check for updated files
        id: updated_files
        run: |
          UPDATED_FILES=$(git diff --name-only | grep '^docs/winget/' || true)
          echo "updated_files<<EOF" >> $GITHUB_OUTPUT
          echo "$UPDATED_FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        if: steps.updated_files.outputs.updated_files != ''
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: auto-sync winget package files"
          branch: ${{ github.head_ref }}
          file_pattern: 'docs/winget/*.json'

      - name: Comment on PR with updated files
        if: steps.updated_files.outputs.updated_files != ''
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const updatedFiles = `${{ steps.updated_files.outputs.updated_files }}`.split('\n').filter(f => f.trim() !== '');
            if (updatedFiles.length > 0) {
              const msg = [
                "The following files were updated by the sync workflow:\n",
                "```\n",
                ...updatedFiles.map(f => `- ${f}`),
                "\n```"
              ].join('');
              const prNumber = context.payload.pull_request.number;
              github.rest.issues.createComment({
                ...context.repo,
                issue_number: prNumber,
                body: msg
              });
            }
