name: Sync Winget Packages

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'winget/**'

jobs:
  sync-packages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run sync_packages.py
        working-directory: winget
        run: |
          python3 sync_packages.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: auto-sync winget package files"
          branch: ${{ github.head_ref }}
          file_pattern: 'docs/winget/*.json'

      - name: Comment on PR with updated files
        if: always()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { execSync } = require('child_process');
            const updatedFiles = execSync('git diff --name-only HEAD^ HEAD')
              .toString()
              .split('\n')
              .filter(f => f.startsWith('docs/winget/'))
              .filter(f => f.trim() !== '');
            if (updatedFiles.length > 0) {
              const msg = [
                "The following files were updated by the sync workflow:\n",
                "```\n",
                ...updatedFiles.map(f => `- ${f}`),
                "\n```"
              ].join('');
              const prNumber = context.payload.pull_request.number;
              github.rest.issues.createComment({
                ...context.repo,
                issue_number: prNumber,
                body: msg
              });
            }
